### PR TITLE
use jspm API to generate package importmap

### PR DESCRIPTION
**Pull request by fusionstrings**

### CODE REVIEW

**Comment by fusionstrings** [comment]
> Whenever possible I would recommend doing the in-browser generation. The API is more for environments that aren't able to do that.

I agree @guybedford .
Due to https://github.com/jspm/jspm-packages/issues/18 and since the generator doesn't work yet in Deno (for SSR) I resorted to this temporarily.

Do you think it's a valid usecase?

**Comment by guybedford** [comment]
@fusionstrings can we not do the generation on the client?

**Comment by fusionstrings** [comment]
> @fusionstrings can we not do the generation on the client?

I am investigating what might be wrong. So far this REPL works https://replit.com/@fusionstrings/jspm-packages-pull-23
https://jspm-packages-pull-23.fusionstrings.repl.co

**Comment by fusionstrings** [comment]
> @fusionstrings can we not do the generation on the client?

@guybedford here is [another attempt ](https://github.com/jspm/jspm-packages/pull/25)to generate hash URLs but hashes are incorrect. Any idea what is wrong here? I am using same `stateToHash` function as in [generator.jspm.io](https://github.com/jspm/generator.jspm.io/blob/main/src/statehash.js#L121)

**Comment by fusionstrings** [comment]
fixed and superseded by https://github.com/jspm/jspm-packages/pull/25.

**Pull request closed without merging**
