### PR TITLE
add dom script

### PR DESCRIPTION
**Pull request by fusionstrings**

### CODE REVIEW

**Comment by guybedford** [comment]
@fusionstrings I've updated the Chomp `"jspm"` template so that when `target = "x.importmap"` it will generate an import map instead of HTML for the deps being JS files provided.

**Comment by fusionstrings** [comment]
> @fusionstrings I've updated the Chomp `"jspm"` template so that when `target = "x.importmap"` it will generate an import map instead of HTML for the deps being JS files provided.

Thanks for taking a look @guybedford  :)
While on that, I found that I need to run `deno run -A --unstable --watch server.js` manually, it doesn't fire as part of chomp [task orchestration](https://github.com/jspm/jspm-packages/pull/9/files#diff-c6f24c8d4986a981208ce222ee8d62600a5fb439945caeb6a2d044a6e84856f3R6).

**Comment by guybedford** [comment]
@fusionstrings did you try run `chomp deno`?

**Comment by guybedford** [comment]
I've posted an issue in https://github.com/guybedford/chomp/issues/44 to support the Chomp watcher invalidating Deno.

**Comment by fusionstrings** [comment]
> @fusionstrings did you try run `chomp deno`?

Does it need to be running separately than `chomp`? I thought running just `chomp` would run `deno`task as well.

**Comment by guybedford** [comment]
Chomp will run the `"build"` task by default, which in this case is separate to the `"deno"` task.

**Comment by fusionstrings** [comment]
> guybedford/chomp#44

ahha, I wasn't aware, thanks :)
Is there then any other way to run `deno` task after `build` finishes, the way we have `deps` for tasks which should run before?

**Comment by fusionstrings** [comment]
> Chomp will run the `"build"` task by default, which in this case is separate to the `"deno"` task.

Is there then any other way to run deno task after build finishes, the way we have deps for tasks which should run before?

**Comment by guybedford** [comment]
@fusionstrings because `deno` depends on `build` it will always run the build first.

**Comment by fusionstrings** [comment]
seems to be functional now.
There is big performance issue, I am gonna take care in a different PR.

**Pull request merged**
