### PR TITLE
render importmap

### PR DESCRIPTION
**Pull request by fusionstrings**

### CODE REVIEW

**Comment by JayaKrishnaNamburu** [comment]
Hey, looks cool. But can we make it resolve by opening `generator.jspm.io` instead of here.

**Comment by fusionstrings** [comment]
main issue here still needed to solve is that detail element closes on update

**Comment by fusionstrings** [comment]
> Hey, looks cool. But can we make it resolve by opening `generator.jspm.io` instead of here.

How do we do it?
Looked into it but couldn't follow.

**Comment by guybedford** [comment]
The generator URL hash construction is implemented here - https://github.com/jspm/generator.jspm.io/blob/main/src/statehash.js.

**Comment by fusionstrings** [comment]
The layout is wider now to accommodate open detail elements.

**Pull request merged**
